[package]
name = "Hanafuda: Akaviri Playing Cards"
description = "Let's play Koi-Koi with Hanafuda in Morrowind."
homepage = "https://www.nexusmods.com/morrowind/mods/53104"
repository = "https://github.com/longod/Hanafuda"
authors = ["longod"]
version = "1.0.0"

[tools.mwse]
lua-mod = "Hanafuda"
load-order = 100
wait-until-initialized = true

[dependencies]
assets = [
    "Textures\\Hanafuda"
]

[dependencies.mwse]
buildnumber = 3243

[dependencies.mge-xe]
version = ">=0.15.0"
