-- UI_ID , not UUID
local this = {
    gameMenu = tes3ui.registerID("KoiKoi"),
    grabMenu = tes3ui.registerID("KoiKoiGrab"),
    splashMenu = tes3ui.registerID("KoiKoiSplash"),
    playerHand = tes3ui.registerID("Player.Hand"),
    playerBright = tes3ui.registerID("Player.Bright"),
    playerAnimal = tes3ui.registerID("Player.Animal"),
    playerRibbon = tes3ui.registerID("Player.Ribbon"),
    playerChaff = tes3ui.registerID("Player.Chaff"),
    playerScore = tes3ui.registerID("Player.Score"),
    playerCombination = tes3ui.registerID("Player.Combination"),
    opponentHand = tes3ui.registerID("Opponent.Hand"),
    opponentBright = tes3ui.registerID("Opponent.Bright"),
    opponentAnimal = tes3ui.registerID("Opponent.Animal"),
    opponentRibbon = tes3ui.registerID("Opponent.Ribbon"),
    opponentChaff = tes3ui.registerID("Opponent.Chaff"),
    opponentScore = tes3ui.registerID("Opponent.Score"),
    opponentCombination = tes3ui.registerID("Opponent.Combination"),
    boardPile = tes3ui.registerID("Board.Pile"),
    boardDrawn = tes3ui.registerID("Board.Drawn"),
    boardGroundRow0 = tes3ui.registerID("Board.GroundRow0"),
    boardGroundRow1 = tes3ui.registerID("Board.GroundRow1"),
    boardRound = tes3ui.registerID("Board.Round"),
}
return this
